Improve docs architecture
neo4j/docs-spark pull request #34
Opened 2024-02-22 15:34 UTC by nvitucci

So far:

- Move content of "Overview" into the index page (which was just a TOC)
- Add section dividers
- Split "Quickstart"
- Split "Reading" and "Writing" pages
- Add new "Databricks" page with content from other pages
- Reorganized other sections

~Names for pages and sections are a WIP as long as the PR is in draft state.~

~In this iteration I am not changing any content, except when moving some parts to a different page (for example when splitting a long page into shorter ones).~ I have updated content wherever it improved consistency and readability.

2024-02-22 15:35 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [General considerations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Read data with a custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/writing-cypher)

Updated pages:
- [Using with Neo4j AuraDB](https://neo4j-docs-spark-34.surge.sh/spark/5/aura)
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Writing to Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/writing)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-02-26 11:31 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [General considerations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/writing-cypher)

Updated pages:
- [Using with Neo4j AuraDB](https://neo4j-docs-spark-34.surge.sh/spark/5/aura)
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Writing to Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/writing)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-02-28 15:03 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [General considerations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Schema](https://neo4j-docs-spark-34.surge.sh/spark/5/schema)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/writing-cypher)

Updated pages:
- [Using with Neo4j AuraDB](https://neo4j-docs-spark-34.surge.sh/spark/5/aura)
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Writing to Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/writing)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-01 15:32 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark features](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/azure-synapse-analytics)
- [BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/bigquery)
- [Interacting with Data Warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Schema](https://neo4j-docs-spark-34.surge.sh/spark/5/schema)

Updated pages:
- [Using with Neo4j AuraDB](https://neo4j-docs-spark-34.surge.sh/spark/5/aura)
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Data type mapping](https://neo4j-docs-spark-34.surge.sh/spark/5/types)
- [Writing to Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/writing)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-01 15:49 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark features](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/azure-synapse-analytics)
- [BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/bigquery)
- [Interacting with Data Warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [User defined schema](https://neo4j-docs-spark-34.surge.sh/spark/5/schema-user)

Updated pages:
- [Using with Neo4j AuraDB](https://neo4j-docs-spark-34.surge.sh/spark/5/aura)
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Data type mapping](https://neo4j-docs-spark-34.surge.sh/spark/5/types)
- [Writing to Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/writing)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-04 11:41 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark features](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [User defined schema](https://neo4j-docs-spark-34.surge.sh/spark/5/schema-user)

Updated pages:
- [Using with Neo4j AuraDB](https://neo4j-docs-spark-34.surge.sh/spark/5/aura)
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Data type mapping](https://neo4j-docs-spark-34.surge.sh/spark/5/types)
- [Writing to Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/writing)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-04 11:48 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark features](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [User defined schema](https://neo4j-docs-spark-34.surge.sh/spark/5/schema-user)

Updated pages:
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Data type mapping](https://neo4j-docs-spark-34.surge.sh/spark/5/types)
- [Writing to Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/writing)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-04 16:58 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark features](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)
- [User defined schema](https://neo4j-docs-spark-34.surge.sh/spark/5/schema-user)

Updated pages:
- [Architecture guidance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Data type mapping](https://neo4j-docs-spark-34.surge.sh/spark/5/types)
- [Writing to Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/writing)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-05 11:02 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark features](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)
- [User defined schema](https://neo4j-docs-spark-34.surge.sh/spark/5/schema-user)

Updated pages:
- [Architecture guidance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Data type mapping](https://neo4j-docs-spark-34.surge.sh/spark/5/types)
- [Writing to Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/writing)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-05 11:23 UTC, stumoore requested changes
Please use neo4j protocol throughout

2024-03-05 11:23 UTC, stumoore commented on modules/ROOT/pages/quickstart.adoc
> +  .option("url", "bolt://localhost:7687") \
Please use neo4j protocol

2024-03-05 11:52 UTC, stumoore requested changes

2024-03-05 11:52 UTC, stumoore commented on modules/ROOT/pages/index.adoc
> +The Neo4j Connector for Apache Spark is intended to make integrating graphs with Spark easy.
```suggestion
The Neo4j Connector for Apache Spark can be used to transfer data to and from Neo4j to Spark based platforms including Apache Spark, Databricks and data warehouses like Snowflake, and Amazon Redshift. Please refer to xref:dwh.adoc[].
```

2024-03-05 11:52 UTC, stumoore commented on modules/ROOT/pages/index.adoc
> + as a cluster, or a managed service in Neo4j AuraDB.
```suggestion
 as a cluster, or a managed service in Neo4j Aura.
```

2024-03-05 11:52 UTC, stumoore commented on modules/ROOT/pages/index.adoc
> +The connector does not rely on any Enterprise Edition features and as
```suggestion
The connector supports Community and Enterprise Edition, however schema optimization is only available on Enterprise.
```

2024-03-05 13:04 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark features](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)
- [User defined schema](https://neo4j-docs-spark-34.surge.sh/spark/5/schema-user)

Updated pages:
- [Architecture guidance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Data type mapping](https://neo4j-docs-spark-34.surge.sh/spark/5/types)
- [Writing to Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/writing)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-05 13:04 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark features](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)
- [User defined schema](https://neo4j-docs-spark-34.surge.sh/spark/5/schema-user)

Updated pages:
- [Architecture guidance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Data type mapping](https://neo4j-docs-spark-34.surge.sh/spark/5/types)
- [Writing to Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/writing)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-05 13:11 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark features](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)
- [User defined schema](https://neo4j-docs-spark-34.surge.sh/spark/5/schema-user)

Updated pages:
- [Architecture guidance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Using Spark Structured Streaming API](https://neo4j-docs-spark-34.surge.sh/spark/5/streaming)
- [Data type mapping](https://neo4j-docs-spark-34.surge.sh/spark/5/types)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-05 16:45 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark features](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)
- [User defined schema](https://neo4j-docs-spark-34.surge.sh/spark/5/schema-user)

Updated pages:
- [Architecture guidance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Using Spark Structured Streaming API](https://neo4j-docs-spark-34.surge.sh/spark/5/streaming)
- [Data type mapping](https://neo4j-docs-spark-34.surge.sh/spark/5/types)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-06 11:35 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark features](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)
- [User defined schema](https://neo4j-docs-spark-34.surge.sh/spark/5/schema-user)

Updated pages:
- [Architecture guidance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Using Spark Structured Streaming API](https://neo4j-docs-spark-34.surge.sh/spark/5/streaming)
- [Data type mapping](https://neo4j-docs-spark-34.surge.sh/spark/5/types)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-06 12:25 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark features](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Databricks](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)
- [User defined schema](https://neo4j-docs-spark-34.surge.sh/spark/5/schema-user)

Updated pages:
- [Architecture guidance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Neo4j Spark Connector options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Using Spark Structured Streaming API](https://neo4j-docs-spark-34.surge.sh/spark/5/streaming)
- [Data type mapping](https://neo4j-docs-spark-34.surge.sh/spark/5/types)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-11 11:13 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-11 14:38 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-11 15:02 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-11 16:33 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-11 17:28 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-11 17:37 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-18 17:14 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-19 11:08 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-19 11:16 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-19 12:12 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-19 15:54 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/redshift)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-19 17:01 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Read options](https://neo4j-docs-spark-34.surge.sh/spark/5/read-options)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-20 09:36 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Read options](https://neo4j-docs-spark-34.surge.sh/spark/5/read-options)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-20 11:56 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Read options](https://neo4j-docs-spark-34.surge.sh/spark/5/read-options)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-20 12:21 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Read options](https://neo4j-docs-spark-34.surge.sh/spark/5/read-options)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/reading-cypher)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-21 15:50 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/read-query)
- [Reader options](https://neo4j-docs-spark-34.surge.sh/spark/5/reader-options)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-21 17:04 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/read-query)
- [Reader options](https://neo4j-docs-spark-34.surge.sh/spark/5/reader-options)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [Connector FAQ](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-22 12:04 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/read-query)
- [Reader options](https://neo4j-docs-spark-34.surge.sh/spark/5/reader-options)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-22 17:49 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/read-query)
- [Reader options](https://neo4j-docs-spark-34.surge.sh/spark/5/reader-options)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-25 12:19 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/bigquery)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)
- [Custom Cypher query](https://neo4j-docs-spark-34.surge.sh/spark/5/read-query)
- [Reader options](https://neo4j-docs-spark-34.surge.sh/spark/5/reader-options)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-25 12:50 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-25 14:27 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-26 12:48 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-26 17:26 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-26 18:05 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-27 00:04 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-27 12:12 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-27 12:40 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-28 00:19 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-28 10:53 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-28 11:01 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/considerations)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Performance tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance)

Updated pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-28 12:27 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/data-modeling)
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)

Updated pages:
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Spark Structured Streaming](https://neo4j-docs-spark-34.surge.sh/spark/5/streaming)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-28 17:45 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)

Updated pages:
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Spark Structured Streaming](https://neo4j-docs-spark-34.surge.sh/spark/5/streaming)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-03-28 20:50 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)

Updated pages:
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Spark Structured Streaming](https://neo4j-docs-spark-34.surge.sh/spark/5/streaming)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-03 16:02 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)

Updated pages:
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Spark Structured Streaming](https://neo4j-docs-spark-34.surge.sh/spark/5/streaming)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-04 09:10 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Databricks setup](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)

Updated pages:
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
- [Spark Structured Streaming](https://neo4j-docs-spark-34.surge.sh/spark/5/streaming)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-23 14:56 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Read nodes](https://neo4j-docs-spark-34.surge.sh/spark/5/read/labels)

Updated pages:
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-23 15:04 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Read nodes](https://neo4j-docs-spark-34.surge.sh/spark/5/read/labels)

Updated pages:
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-24 15:58 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Read nodes](https://neo4j-docs-spark-34.surge.sh/spark/5/read/labels)

Updated pages:
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-24 16:04 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Define a schema](https://neo4j-docs-spark-34.surge.sh/spark/5/read/define-schema)

Updated pages:
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-24 16:21 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Define a schema](https://neo4j-docs-spark-34.surge.sh/spark/5/read/define-schema)

Updated pages:
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-25 08:36 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Define a schema](https://neo4j-docs-spark-34.surge.sh/spark/5/read/define-schema)

Updated pages:
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-25 09:02 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Define a schema](https://neo4j-docs-spark-34.surge.sh/spark/5/read/define-schema)

Updated pages:
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-25 09:29 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Define a schema](https://neo4j-docs-spark-34.surge.sh/spark/5/read/define-schema)

Updated pages:
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Graph Keys](https://neo4j-docs-spark-34.surge.sh/spark/5/graphkeys)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-25 09:41 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Define a schema](https://neo4j-docs-spark-34.surge.sh/spark/5/read/define-schema)

Updated pages:
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-25 13:59 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Define a schema](https://neo4j-docs-spark-34.surge.sh/spark/5/read/define-schema)

Updated pages:
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-25 14:00 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Define a schema](https://neo4j-docs-spark-34.surge.sh/spark/5/read/define-schema)

Updated pages:
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-25 14:10 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Define a schema](https://neo4j-docs-spark-34.surge.sh/spark/5/read/define-schema)

Updated pages:
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-25 14:12 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Define a schema](https://neo4j-docs-spark-34.surge.sh/spark/5/read/define-schema)

Updated pages:
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-25 15:08 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Define a schema](https://neo4j-docs-spark-34.surge.sh/spark/5/read/define-schema)

Updated pages:
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-25 15:27 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-spark-34.surge.sh

New pages:
- [Azure Synapse Analytics](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/azure-synapse-analytics)
- [Google BigQuery](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/bigquery)
- [Amazon Redshift](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/redshift)
- [Snowflake](https://neo4j-docs-spark-34.surge.sh/spark/5/data-warehouses/snowflake)
- [Installation](https://neo4j-docs-spark-34.surge.sh/spark/5/installation)
- [Data modeling](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/modeling)
- [Spark optimizations](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/spark)
- [Parameter tuning](https://neo4j-docs-spark-34.surge.sh/spark/5/performance/tuning)
- [Define a schema](https://neo4j-docs-spark-34.surge.sh/spark/5/read/define-schema)

Updated pages:
- [Improving performance](https://neo4j-docs-spark-34.surge.sh/spark/5/architecture)
- [Options and configuration](https://neo4j-docs-spark-34.surge.sh/spark/5/configuration)
- [Databricks quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/databricks)
- [Data warehouses](https://neo4j-docs-spark-34.surge.sh/spark/5/dwh)
- [FAQ and troubleshooting](https://neo4j-docs-spark-34.surge.sh/spark/5/faq)
- [Data science with Neo4j GDS](https://neo4j-docs-spark-34.surge.sh/spark/5/gds)
- [Neo4j Connector for Apache Spark](https://neo4j-docs-spark-34.surge.sh/spark/5)
- [Quickstart](https://neo4j-docs-spark-34.surge.sh/spark/5/quickstart)
- [Reading from Neo4j](https://neo4j-docs-spark-34.surge.sh/spark/5/reading)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-04-26 08:25 UTC, fbiville approved these changes

2024-04-26 09:04 UTC, stumoore approved these changes
Fantastic restructure and grouping of relevant info

2024-04-26 10:00 UTC, merged